// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: election.proto

package pipe.election;

public final class Election {
  private Election() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  public interface LeaderStatusOrBuilder extends
      // @@protoc_insertion_point(interface_extends:LeaderStatus)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <pre>
     *required LeaderQuery action = 1;
     *optional LeaderState state = 2;
     *optional string leader_host= 3;
     * </pre>
     *
     * <code>optional int32 leader_id = 1;</code>
     */
    boolean hasLeaderId();
    /**
     * <pre>
     *required LeaderQuery action = 1;
     *optional LeaderState state = 2;
     *optional string leader_host= 3;
     * </pre>
     *
     * <code>optional int32 leader_id = 1;</code>
     */
    int getLeaderId();

    /**
     * <code>optional int32 leader_term = 2;</code>
     */
    boolean hasLeaderTerm();
    /**
     * <code>optional int32 leader_term = 2;</code>
     */
    int getLeaderTerm();
  }
  /**
   * <pre>
   * enquire about the state of the leader/election
   * </pre>
   *
   * Protobuf type {@code LeaderStatus}
   */
  public  static final class LeaderStatus extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:LeaderStatus)
      LeaderStatusOrBuilder {
    // Use LeaderStatus.newBuilder() to construct.
    private LeaderStatus(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private LeaderStatus() {
      leaderId_ = 0;
      leaderTerm_ = 0;
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    private LeaderStatus(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!parseUnknownField(input, unknownFields,
                                     extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
            case 8: {
              bitField0_ |= 0x00000001;
              leaderId_ = input.readInt32();
              break;
            }
            case 16: {
              bitField0_ |= 0x00000002;
              leaderTerm_ = input.readInt32();
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return pipe.election.Election.internal_static_LeaderStatus_descriptor;
    }

    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return pipe.election.Election.internal_static_LeaderStatus_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              pipe.election.Election.LeaderStatus.class, pipe.election.Election.LeaderStatus.Builder.class);
    }

    private int bitField0_;
    public static final int LEADER_ID_FIELD_NUMBER = 1;
    private int leaderId_;
    /**
     * <pre>
     *required LeaderQuery action = 1;
     *optional LeaderState state = 2;
     *optional string leader_host= 3;
     * </pre>
     *
     * <code>optional int32 leader_id = 1;</code>
     */
    public boolean hasLeaderId() {
      return ((bitField0_ & 0x00000001) == 0x00000001);
    }
    /**
     * <pre>
     *required LeaderQuery action = 1;
     *optional LeaderState state = 2;
     *optional string leader_host= 3;
     * </pre>
     *
     * <code>optional int32 leader_id = 1;</code>
     */
    public int getLeaderId() {
      return leaderId_;
    }

    public static final int LEADER_TERM_FIELD_NUMBER = 2;
    private int leaderTerm_;
    /**
     * <code>optional int32 leader_term = 2;</code>
     */
    public boolean hasLeaderTerm() {
      return ((bitField0_ & 0x00000002) == 0x00000002);
    }
    /**
     * <code>optional int32 leader_term = 2;</code>
     */
    public int getLeaderTerm() {
      return leaderTerm_;
    }

    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        output.writeInt32(1, leaderId_);
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        output.writeInt32(2, leaderTerm_);
      }
      unknownFields.writeTo(output);
    }

    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(1, leaderId_);
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(2, leaderTerm_);
      }
      size += unknownFields.getSerializedSize();
      memoizedSize = size;
      return size;
    }

    private static final long serialVersionUID = 0L;
    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof pipe.election.Election.LeaderStatus)) {
        return super.equals(obj);
      }
      pipe.election.Election.LeaderStatus other = (pipe.election.Election.LeaderStatus) obj;

      boolean result = true;
      result = result && (hasLeaderId() == other.hasLeaderId());
      if (hasLeaderId()) {
        result = result && (getLeaderId()
            == other.getLeaderId());
      }
      result = result && (hasLeaderTerm() == other.hasLeaderTerm());
      if (hasLeaderTerm()) {
        result = result && (getLeaderTerm()
            == other.getLeaderTerm());
      }
      result = result && unknownFields.equals(other.unknownFields);
      return result;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      if (hasLeaderId()) {
        hash = (37 * hash) + LEADER_ID_FIELD_NUMBER;
        hash = (53 * hash) + getLeaderId();
      }
      if (hasLeaderTerm()) {
        hash = (37 * hash) + LEADER_TERM_FIELD_NUMBER;
        hash = (53 * hash) + getLeaderTerm();
      }
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static pipe.election.Election.LeaderStatus parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static pipe.election.Election.LeaderStatus parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static pipe.election.Election.LeaderStatus parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static pipe.election.Election.LeaderStatus parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static pipe.election.Election.LeaderStatus parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static pipe.election.Election.LeaderStatus parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static pipe.election.Election.LeaderStatus parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static pipe.election.Election.LeaderStatus parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static pipe.election.Election.LeaderStatus parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static pipe.election.Election.LeaderStatus parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(pipe.election.Election.LeaderStatus prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * <pre>
     * enquire about the state of the leader/election
     * </pre>
     *
     * Protobuf type {@code LeaderStatus}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:LeaderStatus)
        pipe.election.Election.LeaderStatusOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return pipe.election.Election.internal_static_LeaderStatus_descriptor;
      }

      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return pipe.election.Election.internal_static_LeaderStatus_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                pipe.election.Election.LeaderStatus.class, pipe.election.Election.LeaderStatus.Builder.class);
      }

      // Construct using pipe.election.Election.LeaderStatus.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
        }
      }
      public Builder clear() {
        super.clear();
        leaderId_ = 0;
        bitField0_ = (bitField0_ & ~0x00000001);
        leaderTerm_ = 0;
        bitField0_ = (bitField0_ & ~0x00000002);
        return this;
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return pipe.election.Election.internal_static_LeaderStatus_descriptor;
      }

      public pipe.election.Election.LeaderStatus getDefaultInstanceForType() {
        return pipe.election.Election.LeaderStatus.getDefaultInstance();
      }

      public pipe.election.Election.LeaderStatus build() {
        pipe.election.Election.LeaderStatus result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public pipe.election.Election.LeaderStatus buildPartial() {
        pipe.election.Election.LeaderStatus result = new pipe.election.Election.LeaderStatus(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (((from_bitField0_ & 0x00000001) == 0x00000001)) {
          to_bitField0_ |= 0x00000001;
        }
        result.leaderId_ = leaderId_;
        if (((from_bitField0_ & 0x00000002) == 0x00000002)) {
          to_bitField0_ |= 0x00000002;
        }
        result.leaderTerm_ = leaderTerm_;
        result.bitField0_ = to_bitField0_;
        onBuilt();
        return result;
      }

      public Builder clone() {
        return (Builder) super.clone();
      }
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          Object value) {
        return (Builder) super.setField(field, value);
      }
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return (Builder) super.clearField(field);
      }
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return (Builder) super.clearOneof(oneof);
      }
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, Object value) {
        return (Builder) super.setRepeatedField(field, index, value);
      }
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          Object value) {
        return (Builder) super.addRepeatedField(field, value);
      }
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof pipe.election.Election.LeaderStatus) {
          return mergeFrom((pipe.election.Election.LeaderStatus)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(pipe.election.Election.LeaderStatus other) {
        if (other == pipe.election.Election.LeaderStatus.getDefaultInstance()) return this;
        if (other.hasLeaderId()) {
          setLeaderId(other.getLeaderId());
        }
        if (other.hasLeaderTerm()) {
          setLeaderTerm(other.getLeaderTerm());
        }
        this.mergeUnknownFields(other.unknownFields);
        onChanged();
        return this;
      }

      public final boolean isInitialized() {
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        pipe.election.Election.LeaderStatus parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (pipe.election.Election.LeaderStatus) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      private int leaderId_ ;
      /**
       * <pre>
       *required LeaderQuery action = 1;
       *optional LeaderState state = 2;
       *optional string leader_host= 3;
       * </pre>
       *
       * <code>optional int32 leader_id = 1;</code>
       */
      public boolean hasLeaderId() {
        return ((bitField0_ & 0x00000001) == 0x00000001);
      }
      /**
       * <pre>
       *required LeaderQuery action = 1;
       *optional LeaderState state = 2;
       *optional string leader_host= 3;
       * </pre>
       *
       * <code>optional int32 leader_id = 1;</code>
       */
      public int getLeaderId() {
        return leaderId_;
      }
      /**
       * <pre>
       *required LeaderQuery action = 1;
       *optional LeaderState state = 2;
       *optional string leader_host= 3;
       * </pre>
       *
       * <code>optional int32 leader_id = 1;</code>
       */
      public Builder setLeaderId(int value) {
        bitField0_ |= 0x00000001;
        leaderId_ = value;
        onChanged();
        return this;
      }
      /**
       * <pre>
       *required LeaderQuery action = 1;
       *optional LeaderState state = 2;
       *optional string leader_host= 3;
       * </pre>
       *
       * <code>optional int32 leader_id = 1;</code>
       */
      public Builder clearLeaderId() {
        bitField0_ = (bitField0_ & ~0x00000001);
        leaderId_ = 0;
        onChanged();
        return this;
      }

      private int leaderTerm_ ;
      /**
       * <code>optional int32 leader_term = 2;</code>
       */
      public boolean hasLeaderTerm() {
        return ((bitField0_ & 0x00000002) == 0x00000002);
      }
      /**
       * <code>optional int32 leader_term = 2;</code>
       */
      public int getLeaderTerm() {
        return leaderTerm_;
      }
      /**
       * <code>optional int32 leader_term = 2;</code>
       */
      public Builder setLeaderTerm(int value) {
        bitField0_ |= 0x00000002;
        leaderTerm_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional int32 leader_term = 2;</code>
       */
      public Builder clearLeaderTerm() {
        bitField0_ = (bitField0_ & ~0x00000002);
        leaderTerm_ = 0;
        onChanged();
        return this;
      }
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFields(unknownFields);
      }

      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:LeaderStatus)
    }

    // @@protoc_insertion_point(class_scope:LeaderStatus)
    private static final pipe.election.Election.LeaderStatus DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new pipe.election.Election.LeaderStatus();
    }

    public static pipe.election.Election.LeaderStatus getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    @java.lang.Deprecated public static final com.google.protobuf.Parser<LeaderStatus>
        PARSER = new com.google.protobuf.AbstractParser<LeaderStatus>() {
      public LeaderStatus parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
          return new LeaderStatus(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<LeaderStatus> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<LeaderStatus> getParserForType() {
      return PARSER;
    }

    public pipe.election.Election.LeaderStatus getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  public interface CandidateStatusOrBuilder extends
      // @@protoc_insertion_point(interface_extends:CandidateStatus)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>optional string candidate_host = 3;</code>
     */
    boolean hasCandidateHost();
    /**
     * <code>optional string candidate_host = 3;</code>
     */
    java.lang.String getCandidateHost();
    /**
     * <code>optional string candidate_host = 3;</code>
     */
    com.google.protobuf.ByteString
        getCandidateHostBytes();

    /**
     * <code>optional int32 candidate_id = 4;</code>
     */
    boolean hasCandidateId();
    /**
     * <code>optional int32 candidate_id = 4;</code>
     */
    int getCandidateId();
  }
  /**
   * Protobuf type {@code CandidateStatus}
   */
  public  static final class CandidateStatus extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:CandidateStatus)
      CandidateStatusOrBuilder {
    // Use CandidateStatus.newBuilder() to construct.
    private CandidateStatus(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private CandidateStatus() {
      candidateHost_ = "";
      candidateId_ = 0;
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    private CandidateStatus(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!parseUnknownField(input, unknownFields,
                                     extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
            case 26: {
              com.google.protobuf.ByteString bs = input.readBytes();
              bitField0_ |= 0x00000001;
              candidateHost_ = bs;
              break;
            }
            case 32: {
              bitField0_ |= 0x00000002;
              candidateId_ = input.readInt32();
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return pipe.election.Election.internal_static_CandidateStatus_descriptor;
    }

    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return pipe.election.Election.internal_static_CandidateStatus_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              pipe.election.Election.CandidateStatus.class, pipe.election.Election.CandidateStatus.Builder.class);
    }

    private int bitField0_;
    public static final int CANDIDATE_HOST_FIELD_NUMBER = 3;
    private volatile java.lang.Object candidateHost_;
    /**
     * <code>optional string candidate_host = 3;</code>
     */
    public boolean hasCandidateHost() {
      return ((bitField0_ & 0x00000001) == 0x00000001);
    }
    /**
     * <code>optional string candidate_host = 3;</code>
     */
    public java.lang.String getCandidateHost() {
      java.lang.Object ref = candidateHost_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        if (bs.isValidUtf8()) {
          candidateHost_ = s;
        }
        return s;
      }
    }
    /**
     * <code>optional string candidate_host = 3;</code>
     */
    public com.google.protobuf.ByteString
        getCandidateHostBytes() {
      java.lang.Object ref = candidateHost_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        candidateHost_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int CANDIDATE_ID_FIELD_NUMBER = 4;
    private int candidateId_;
    /**
     * <code>optional int32 candidate_id = 4;</code>
     */
    public boolean hasCandidateId() {
      return ((bitField0_ & 0x00000002) == 0x00000002);
    }
    /**
     * <code>optional int32 candidate_id = 4;</code>
     */
    public int getCandidateId() {
      return candidateId_;
    }

    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 3, candidateHost_);
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        output.writeInt32(4, candidateId_);
      }
      unknownFields.writeTo(output);
    }

    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(3, candidateHost_);
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(4, candidateId_);
      }
      size += unknownFields.getSerializedSize();
      memoizedSize = size;
      return size;
    }

    private static final long serialVersionUID = 0L;
    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof pipe.election.Election.CandidateStatus)) {
        return super.equals(obj);
      }
      pipe.election.Election.CandidateStatus other = (pipe.election.Election.CandidateStatus) obj;

      boolean result = true;
      result = result && (hasCandidateHost() == other.hasCandidateHost());
      if (hasCandidateHost()) {
        result = result && getCandidateHost()
            .equals(other.getCandidateHost());
      }
      result = result && (hasCandidateId() == other.hasCandidateId());
      if (hasCandidateId()) {
        result = result && (getCandidateId()
            == other.getCandidateId());
      }
      result = result && unknownFields.equals(other.unknownFields);
      return result;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      if (hasCandidateHost()) {
        hash = (37 * hash) + CANDIDATE_HOST_FIELD_NUMBER;
        hash = (53 * hash) + getCandidateHost().hashCode();
      }
      if (hasCandidateId()) {
        hash = (37 * hash) + CANDIDATE_ID_FIELD_NUMBER;
        hash = (53 * hash) + getCandidateId();
      }
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static pipe.election.Election.CandidateStatus parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static pipe.election.Election.CandidateStatus parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static pipe.election.Election.CandidateStatus parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static pipe.election.Election.CandidateStatus parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static pipe.election.Election.CandidateStatus parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static pipe.election.Election.CandidateStatus parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static pipe.election.Election.CandidateStatus parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static pipe.election.Election.CandidateStatus parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static pipe.election.Election.CandidateStatus parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static pipe.election.Election.CandidateStatus parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(pipe.election.Election.CandidateStatus prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code CandidateStatus}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:CandidateStatus)
        pipe.election.Election.CandidateStatusOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return pipe.election.Election.internal_static_CandidateStatus_descriptor;
      }

      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return pipe.election.Election.internal_static_CandidateStatus_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                pipe.election.Election.CandidateStatus.class, pipe.election.Election.CandidateStatus.Builder.class);
      }

      // Construct using pipe.election.Election.CandidateStatus.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
        }
      }
      public Builder clear() {
        super.clear();
        candidateHost_ = "";
        bitField0_ = (bitField0_ & ~0x00000001);
        candidateId_ = 0;
        bitField0_ = (bitField0_ & ~0x00000002);
        return this;
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return pipe.election.Election.internal_static_CandidateStatus_descriptor;
      }

      public pipe.election.Election.CandidateStatus getDefaultInstanceForType() {
        return pipe.election.Election.CandidateStatus.getDefaultInstance();
      }

      public pipe.election.Election.CandidateStatus build() {
        pipe.election.Election.CandidateStatus result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public pipe.election.Election.CandidateStatus buildPartial() {
        pipe.election.Election.CandidateStatus result = new pipe.election.Election.CandidateStatus(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (((from_bitField0_ & 0x00000001) == 0x00000001)) {
          to_bitField0_ |= 0x00000001;
        }
        result.candidateHost_ = candidateHost_;
        if (((from_bitField0_ & 0x00000002) == 0x00000002)) {
          to_bitField0_ |= 0x00000002;
        }
        result.candidateId_ = candidateId_;
        result.bitField0_ = to_bitField0_;
        onBuilt();
        return result;
      }

      public Builder clone() {
        return (Builder) super.clone();
      }
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          Object value) {
        return (Builder) super.setField(field, value);
      }
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return (Builder) super.clearField(field);
      }
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return (Builder) super.clearOneof(oneof);
      }
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, Object value) {
        return (Builder) super.setRepeatedField(field, index, value);
      }
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          Object value) {
        return (Builder) super.addRepeatedField(field, value);
      }
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof pipe.election.Election.CandidateStatus) {
          return mergeFrom((pipe.election.Election.CandidateStatus)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(pipe.election.Election.CandidateStatus other) {
        if (other == pipe.election.Election.CandidateStatus.getDefaultInstance()) return this;
        if (other.hasCandidateHost()) {
          bitField0_ |= 0x00000001;
          candidateHost_ = other.candidateHost_;
          onChanged();
        }
        if (other.hasCandidateId()) {
          setCandidateId(other.getCandidateId());
        }
        this.mergeUnknownFields(other.unknownFields);
        onChanged();
        return this;
      }

      public final boolean isInitialized() {
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        pipe.election.Election.CandidateStatus parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (pipe.election.Election.CandidateStatus) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      private java.lang.Object candidateHost_ = "";
      /**
       * <code>optional string candidate_host = 3;</code>
       */
      public boolean hasCandidateHost() {
        return ((bitField0_ & 0x00000001) == 0x00000001);
      }
      /**
       * <code>optional string candidate_host = 3;</code>
       */
      public java.lang.String getCandidateHost() {
        java.lang.Object ref = candidateHost_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          if (bs.isValidUtf8()) {
            candidateHost_ = s;
          }
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>optional string candidate_host = 3;</code>
       */
      public com.google.protobuf.ByteString
          getCandidateHostBytes() {
        java.lang.Object ref = candidateHost_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          candidateHost_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>optional string candidate_host = 3;</code>
       */
      public Builder setCandidateHost(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000001;
        candidateHost_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional string candidate_host = 3;</code>
       */
      public Builder clearCandidateHost() {
        bitField0_ = (bitField0_ & ~0x00000001);
        candidateHost_ = getDefaultInstance().getCandidateHost();
        onChanged();
        return this;
      }
      /**
       * <code>optional string candidate_host = 3;</code>
       */
      public Builder setCandidateHostBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000001;
        candidateHost_ = value;
        onChanged();
        return this;
      }

      private int candidateId_ ;
      /**
       * <code>optional int32 candidate_id = 4;</code>
       */
      public boolean hasCandidateId() {
        return ((bitField0_ & 0x00000002) == 0x00000002);
      }
      /**
       * <code>optional int32 candidate_id = 4;</code>
       */
      public int getCandidateId() {
        return candidateId_;
      }
      /**
       * <code>optional int32 candidate_id = 4;</code>
       */
      public Builder setCandidateId(int value) {
        bitField0_ |= 0x00000002;
        candidateId_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional int32 candidate_id = 4;</code>
       */
      public Builder clearCandidateId() {
        bitField0_ = (bitField0_ & ~0x00000002);
        candidateId_ = 0;
        onChanged();
        return this;
      }
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFields(unknownFields);
      }

      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:CandidateStatus)
    }

    // @@protoc_insertion_point(class_scope:CandidateStatus)
    private static final pipe.election.Election.CandidateStatus DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new pipe.election.Election.CandidateStatus();
    }

    public static pipe.election.Election.CandidateStatus getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    @java.lang.Deprecated public static final com.google.protobuf.Parser<CandidateStatus>
        PARSER = new com.google.protobuf.AbstractParser<CandidateStatus>() {
      public CandidateStatus parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
          return new CandidateStatus(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<CandidateStatus> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<CandidateStatus> getParserForType() {
      return PARSER;
    }

    public pipe.election.Election.CandidateStatus getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  public interface VoteOrBuilder extends
      // @@protoc_insertion_point(interface_extends:Vote)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>required int32 voterID = 2;</code>
     */
    boolean hasVoterID();
    /**
     * <code>required int32 voterID = 2;</code>
     */
    int getVoterID();

    /**
     * <code>optional int32 candidateID = 3;</code>
     */
    boolean hasCandidateID();
    /**
     * <code>optional int32 candidateID = 3;</code>
     */
    int getCandidateID();
  }
  /**
   * Protobuf type {@code Vote}
   */
  public  static final class Vote extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:Vote)
      VoteOrBuilder {
    // Use Vote.newBuilder() to construct.
    private Vote(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private Vote() {
      voterID_ = 0;
      candidateID_ = 0;
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    private Vote(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!parseUnknownField(input, unknownFields,
                                     extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
            case 16: {
              bitField0_ |= 0x00000001;
              voterID_ = input.readInt32();
              break;
            }
            case 24: {
              bitField0_ |= 0x00000002;
              candidateID_ = input.readInt32();
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return pipe.election.Election.internal_static_Vote_descriptor;
    }

    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return pipe.election.Election.internal_static_Vote_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              pipe.election.Election.Vote.class, pipe.election.Election.Vote.Builder.class);
    }

    private int bitField0_;
    public static final int VOTERID_FIELD_NUMBER = 2;
    private int voterID_;
    /**
     * <code>required int32 voterID = 2;</code>
     */
    public boolean hasVoterID() {
      return ((bitField0_ & 0x00000001) == 0x00000001);
    }
    /**
     * <code>required int32 voterID = 2;</code>
     */
    public int getVoterID() {
      return voterID_;
    }

    public static final int CANDIDATEID_FIELD_NUMBER = 3;
    private int candidateID_;
    /**
     * <code>optional int32 candidateID = 3;</code>
     */
    public boolean hasCandidateID() {
      return ((bitField0_ & 0x00000002) == 0x00000002);
    }
    /**
     * <code>optional int32 candidateID = 3;</code>
     */
    public int getCandidateID() {
      return candidateID_;
    }

    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      if (!hasVoterID()) {
        memoizedIsInitialized = 0;
        return false;
      }
      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        output.writeInt32(2, voterID_);
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        output.writeInt32(3, candidateID_);
      }
      unknownFields.writeTo(output);
    }

    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(2, voterID_);
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(3, candidateID_);
      }
      size += unknownFields.getSerializedSize();
      memoizedSize = size;
      return size;
    }

    private static final long serialVersionUID = 0L;
    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof pipe.election.Election.Vote)) {
        return super.equals(obj);
      }
      pipe.election.Election.Vote other = (pipe.election.Election.Vote) obj;

      boolean result = true;
      result = result && (hasVoterID() == other.hasVoterID());
      if (hasVoterID()) {
        result = result && (getVoterID()
            == other.getVoterID());
      }
      result = result && (hasCandidateID() == other.hasCandidateID());
      if (hasCandidateID()) {
        result = result && (getCandidateID()
            == other.getCandidateID());
      }
      result = result && unknownFields.equals(other.unknownFields);
      return result;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      if (hasVoterID()) {
        hash = (37 * hash) + VOTERID_FIELD_NUMBER;
        hash = (53 * hash) + getVoterID();
      }
      if (hasCandidateID()) {
        hash = (37 * hash) + CANDIDATEID_FIELD_NUMBER;
        hash = (53 * hash) + getCandidateID();
      }
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static pipe.election.Election.Vote parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static pipe.election.Election.Vote parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static pipe.election.Election.Vote parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static pipe.election.Election.Vote parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static pipe.election.Election.Vote parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static pipe.election.Election.Vote parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static pipe.election.Election.Vote parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static pipe.election.Election.Vote parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static pipe.election.Election.Vote parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static pipe.election.Election.Vote parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(pipe.election.Election.Vote prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code Vote}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:Vote)
        pipe.election.Election.VoteOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return pipe.election.Election.internal_static_Vote_descriptor;
      }

      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return pipe.election.Election.internal_static_Vote_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                pipe.election.Election.Vote.class, pipe.election.Election.Vote.Builder.class);
      }

      // Construct using pipe.election.Election.Vote.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
        }
      }
      public Builder clear() {
        super.clear();
        voterID_ = 0;
        bitField0_ = (bitField0_ & ~0x00000001);
        candidateID_ = 0;
        bitField0_ = (bitField0_ & ~0x00000002);
        return this;
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return pipe.election.Election.internal_static_Vote_descriptor;
      }

      public pipe.election.Election.Vote getDefaultInstanceForType() {
        return pipe.election.Election.Vote.getDefaultInstance();
      }

      public pipe.election.Election.Vote build() {
        pipe.election.Election.Vote result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public pipe.election.Election.Vote buildPartial() {
        pipe.election.Election.Vote result = new pipe.election.Election.Vote(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (((from_bitField0_ & 0x00000001) == 0x00000001)) {
          to_bitField0_ |= 0x00000001;
        }
        result.voterID_ = voterID_;
        if (((from_bitField0_ & 0x00000002) == 0x00000002)) {
          to_bitField0_ |= 0x00000002;
        }
        result.candidateID_ = candidateID_;
        result.bitField0_ = to_bitField0_;
        onBuilt();
        return result;
      }

      public Builder clone() {
        return (Builder) super.clone();
      }
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          Object value) {
        return (Builder) super.setField(field, value);
      }
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return (Builder) super.clearField(field);
      }
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return (Builder) super.clearOneof(oneof);
      }
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, Object value) {
        return (Builder) super.setRepeatedField(field, index, value);
      }
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          Object value) {
        return (Builder) super.addRepeatedField(field, value);
      }
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof pipe.election.Election.Vote) {
          return mergeFrom((pipe.election.Election.Vote)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(pipe.election.Election.Vote other) {
        if (other == pipe.election.Election.Vote.getDefaultInstance()) return this;
        if (other.hasVoterID()) {
          setVoterID(other.getVoterID());
        }
        if (other.hasCandidateID()) {
          setCandidateID(other.getCandidateID());
        }
        this.mergeUnknownFields(other.unknownFields);
        onChanged();
        return this;
      }

      public final boolean isInitialized() {
        if (!hasVoterID()) {
          return false;
        }
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        pipe.election.Election.Vote parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (pipe.election.Election.Vote) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      private int voterID_ ;
      /**
       * <code>required int32 voterID = 2;</code>
       */
      public boolean hasVoterID() {
        return ((bitField0_ & 0x00000001) == 0x00000001);
      }
      /**
       * <code>required int32 voterID = 2;</code>
       */
      public int getVoterID() {
        return voterID_;
      }
      /**
       * <code>required int32 voterID = 2;</code>
       */
      public Builder setVoterID(int value) {
        bitField0_ |= 0x00000001;
        voterID_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required int32 voterID = 2;</code>
       */
      public Builder clearVoterID() {
        bitField0_ = (bitField0_ & ~0x00000001);
        voterID_ = 0;
        onChanged();
        return this;
      }

      private int candidateID_ ;
      /**
       * <code>optional int32 candidateID = 3;</code>
       */
      public boolean hasCandidateID() {
        return ((bitField0_ & 0x00000002) == 0x00000002);
      }
      /**
       * <code>optional int32 candidateID = 3;</code>
       */
      public int getCandidateID() {
        return candidateID_;
      }
      /**
       * <code>optional int32 candidateID = 3;</code>
       */
      public Builder setCandidateID(int value) {
        bitField0_ |= 0x00000002;
        candidateID_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional int32 candidateID = 3;</code>
       */
      public Builder clearCandidateID() {
        bitField0_ = (bitField0_ & ~0x00000002);
        candidateID_ = 0;
        onChanged();
        return this;
      }
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFields(unknownFields);
      }

      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:Vote)
    }

    // @@protoc_insertion_point(class_scope:Vote)
    private static final pipe.election.Election.Vote DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new pipe.election.Election.Vote();
    }

    public static pipe.election.Election.Vote getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    @java.lang.Deprecated public static final com.google.protobuf.Parser<Vote>
        PARSER = new com.google.protobuf.AbstractParser<Vote>() {
      public Vote parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
          return new Vote(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<Vote> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<Vote> getParserForType() {
      return PARSER;
    }

    public pipe.election.Election.Vote getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  public interface RequestVoteOrBuilder extends
      // @@protoc_insertion_point(interface_extends:RequestVote)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>required int32 currentTerm = 1;</code>
     */
    boolean hasCurrentTerm();
    /**
     * <code>required int32 currentTerm = 1;</code>
     */
    int getCurrentTerm();

    /**
     * <code>required int32 candidateID = 2;</code>
     */
    boolean hasCandidateID();
    /**
     * <code>required int32 candidateID = 2;</code>
     */
    int getCandidateID();
  }
  /**
   * Protobuf type {@code RequestVote}
   */
  public  static final class RequestVote extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:RequestVote)
      RequestVoteOrBuilder {
    // Use RequestVote.newBuilder() to construct.
    private RequestVote(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private RequestVote() {
      currentTerm_ = 0;
      candidateID_ = 0;
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    private RequestVote(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!parseUnknownField(input, unknownFields,
                                     extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
            case 8: {
              bitField0_ |= 0x00000001;
              currentTerm_ = input.readInt32();
              break;
            }
            case 16: {
              bitField0_ |= 0x00000002;
              candidateID_ = input.readInt32();
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return pipe.election.Election.internal_static_RequestVote_descriptor;
    }

    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return pipe.election.Election.internal_static_RequestVote_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              pipe.election.Election.RequestVote.class, pipe.election.Election.RequestVote.Builder.class);
    }

    private int bitField0_;
    public static final int CURRENTTERM_FIELD_NUMBER = 1;
    private int currentTerm_;
    /**
     * <code>required int32 currentTerm = 1;</code>
     */
    public boolean hasCurrentTerm() {
      return ((bitField0_ & 0x00000001) == 0x00000001);
    }
    /**
     * <code>required int32 currentTerm = 1;</code>
     */
    public int getCurrentTerm() {
      return currentTerm_;
    }

    public static final int CANDIDATEID_FIELD_NUMBER = 2;
    private int candidateID_;
    /**
     * <code>required int32 candidateID = 2;</code>
     */
    public boolean hasCandidateID() {
      return ((bitField0_ & 0x00000002) == 0x00000002);
    }
    /**
     * <code>required int32 candidateID = 2;</code>
     */
    public int getCandidateID() {
      return candidateID_;
    }

    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      if (!hasCurrentTerm()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (!hasCandidateID()) {
        memoizedIsInitialized = 0;
        return false;
      }
      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        output.writeInt32(1, currentTerm_);
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        output.writeInt32(2, candidateID_);
      }
      unknownFields.writeTo(output);
    }

    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(1, currentTerm_);
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(2, candidateID_);
      }
      size += unknownFields.getSerializedSize();
      memoizedSize = size;
      return size;
    }

    private static final long serialVersionUID = 0L;
    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof pipe.election.Election.RequestVote)) {
        return super.equals(obj);
      }
      pipe.election.Election.RequestVote other = (pipe.election.Election.RequestVote) obj;

      boolean result = true;
      result = result && (hasCurrentTerm() == other.hasCurrentTerm());
      if (hasCurrentTerm()) {
        result = result && (getCurrentTerm()
            == other.getCurrentTerm());
      }
      result = result && (hasCandidateID() == other.hasCandidateID());
      if (hasCandidateID()) {
        result = result && (getCandidateID()
            == other.getCandidateID());
      }
      result = result && unknownFields.equals(other.unknownFields);
      return result;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      if (hasCurrentTerm()) {
        hash = (37 * hash) + CURRENTTERM_FIELD_NUMBER;
        hash = (53 * hash) + getCurrentTerm();
      }
      if (hasCandidateID()) {
        hash = (37 * hash) + CANDIDATEID_FIELD_NUMBER;
        hash = (53 * hash) + getCandidateID();
      }
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static pipe.election.Election.RequestVote parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static pipe.election.Election.RequestVote parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static pipe.election.Election.RequestVote parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static pipe.election.Election.RequestVote parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static pipe.election.Election.RequestVote parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static pipe.election.Election.RequestVote parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static pipe.election.Election.RequestVote parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static pipe.election.Election.RequestVote parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static pipe.election.Election.RequestVote parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static pipe.election.Election.RequestVote parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(pipe.election.Election.RequestVote prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code RequestVote}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:RequestVote)
        pipe.election.Election.RequestVoteOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return pipe.election.Election.internal_static_RequestVote_descriptor;
      }

      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return pipe.election.Election.internal_static_RequestVote_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                pipe.election.Election.RequestVote.class, pipe.election.Election.RequestVote.Builder.class);
      }

      // Construct using pipe.election.Election.RequestVote.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
        }
      }
      public Builder clear() {
        super.clear();
        currentTerm_ = 0;
        bitField0_ = (bitField0_ & ~0x00000001);
        candidateID_ = 0;
        bitField0_ = (bitField0_ & ~0x00000002);
        return this;
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return pipe.election.Election.internal_static_RequestVote_descriptor;
      }

      public pipe.election.Election.RequestVote getDefaultInstanceForType() {
        return pipe.election.Election.RequestVote.getDefaultInstance();
      }

      public pipe.election.Election.RequestVote build() {
        pipe.election.Election.RequestVote result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public pipe.election.Election.RequestVote buildPartial() {
        pipe.election.Election.RequestVote result = new pipe.election.Election.RequestVote(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (((from_bitField0_ & 0x00000001) == 0x00000001)) {
          to_bitField0_ |= 0x00000001;
        }
        result.currentTerm_ = currentTerm_;
        if (((from_bitField0_ & 0x00000002) == 0x00000002)) {
          to_bitField0_ |= 0x00000002;
        }
        result.candidateID_ = candidateID_;
        result.bitField0_ = to_bitField0_;
        onBuilt();
        return result;
      }

      public Builder clone() {
        return (Builder) super.clone();
      }
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          Object value) {
        return (Builder) super.setField(field, value);
      }
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return (Builder) super.clearField(field);
      }
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return (Builder) super.clearOneof(oneof);
      }
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, Object value) {
        return (Builder) super.setRepeatedField(field, index, value);
      }
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          Object value) {
        return (Builder) super.addRepeatedField(field, value);
      }
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof pipe.election.Election.RequestVote) {
          return mergeFrom((pipe.election.Election.RequestVote)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(pipe.election.Election.RequestVote other) {
        if (other == pipe.election.Election.RequestVote.getDefaultInstance()) return this;
        if (other.hasCurrentTerm()) {
          setCurrentTerm(other.getCurrentTerm());
        }
        if (other.hasCandidateID()) {
          setCandidateID(other.getCandidateID());
        }
        this.mergeUnknownFields(other.unknownFields);
        onChanged();
        return this;
      }

      public final boolean isInitialized() {
        if (!hasCurrentTerm()) {
          return false;
        }
        if (!hasCandidateID()) {
          return false;
        }
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        pipe.election.Election.RequestVote parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (pipe.election.Election.RequestVote) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      private int currentTerm_ ;
      /**
       * <code>required int32 currentTerm = 1;</code>
       */
      public boolean hasCurrentTerm() {
        return ((bitField0_ & 0x00000001) == 0x00000001);
      }
      /**
       * <code>required int32 currentTerm = 1;</code>
       */
      public int getCurrentTerm() {
        return currentTerm_;
      }
      /**
       * <code>required int32 currentTerm = 1;</code>
       */
      public Builder setCurrentTerm(int value) {
        bitField0_ |= 0x00000001;
        currentTerm_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required int32 currentTerm = 1;</code>
       */
      public Builder clearCurrentTerm() {
        bitField0_ = (bitField0_ & ~0x00000001);
        currentTerm_ = 0;
        onChanged();
        return this;
      }

      private int candidateID_ ;
      /**
       * <code>required int32 candidateID = 2;</code>
       */
      public boolean hasCandidateID() {
        return ((bitField0_ & 0x00000002) == 0x00000002);
      }
      /**
       * <code>required int32 candidateID = 2;</code>
       */
      public int getCandidateID() {
        return candidateID_;
      }
      /**
       * <code>required int32 candidateID = 2;</code>
       */
      public Builder setCandidateID(int value) {
        bitField0_ |= 0x00000002;
        candidateID_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required int32 candidateID = 2;</code>
       */
      public Builder clearCandidateID() {
        bitField0_ = (bitField0_ & ~0x00000002);
        candidateID_ = 0;
        onChanged();
        return this;
      }
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFields(unknownFields);
      }

      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:RequestVote)
    }

    // @@protoc_insertion_point(class_scope:RequestVote)
    private static final pipe.election.Election.RequestVote DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new pipe.election.Election.RequestVote();
    }

    public static pipe.election.Election.RequestVote getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    @java.lang.Deprecated public static final com.google.protobuf.Parser<RequestVote>
        PARSER = new com.google.protobuf.AbstractParser<RequestVote>() {
      public RequestVote parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
          return new RequestVote(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<RequestVote> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<RequestVote> getParserForType() {
      return PARSER;
    }

    public pipe.election.Election.RequestVote getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_LeaderStatus_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_LeaderStatus_fieldAccessorTable;
  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_CandidateStatus_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_CandidateStatus_fieldAccessorTable;
  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_Vote_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_Vote_fieldAccessorTable;
  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_RequestVote_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_RequestVote_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\016election.proto\"6\n\014LeaderStatus\022\021\n\tlead" +
      "er_id\030\001 \001(\005\022\023\n\013leader_term\030\002 \001(\005\"?\n\017Cand" +
      "idateStatus\022\026\n\016candidate_host\030\003 \001(\t\022\024\n\014c" +
      "andidate_id\030\004 \001(\005\",\n\004Vote\022\017\n\007voterID\030\002 \002" +
      "(\005\022\023\n\013candidateID\030\003 \001(\005\"7\n\013RequestVote\022\023" +
      "\n\013currentTerm\030\001 \002(\005\022\023\n\013candidateID\030\002 \002(\005" +
      "B\021\n\rpipe.electionH\001"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
        new com.google.protobuf.Descriptors.FileDescriptor.    InternalDescriptorAssigner() {
          public com.google.protobuf.ExtensionRegistry assignDescriptors(
              com.google.protobuf.Descriptors.FileDescriptor root) {
            descriptor = root;
            return null;
          }
        };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
    internal_static_LeaderStatus_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_LeaderStatus_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_LeaderStatus_descriptor,
        new java.lang.String[] { "LeaderId", "LeaderTerm", });
    internal_static_CandidateStatus_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_CandidateStatus_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_CandidateStatus_descriptor,
        new java.lang.String[] { "CandidateHost", "CandidateId", });
    internal_static_Vote_descriptor =
      getDescriptor().getMessageTypes().get(2);
    internal_static_Vote_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_Vote_descriptor,
        new java.lang.String[] { "VoterID", "CandidateID", });
    internal_static_RequestVote_descriptor =
      getDescriptor().getMessageTypes().get(3);
    internal_static_RequestVote_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_RequestVote_descriptor,
        new java.lang.String[] { "CurrentTerm", "CandidateID", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
