// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: pipe.proto

package routing;

public final class Pipe {
  private Pipe() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  public interface CommandMessageOrBuilder extends
      // @@protoc_insertion_point(interface_extends:CommandMessage)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>required .Header header = 1;</code>
     */
    boolean hasHeader();
    /**
     * <code>required .Header header = 1;</code>
     */
    pipe.common.Common.Header getHeader();
    /**
     * <code>required .Header header = 1;</code>
     */
    pipe.common.Common.HeaderOrBuilder getHeaderOrBuilder();

    /**
     * <pre>
     * a client (external) sanity check for testing
     * </pre>
     *
     * <code>optional bool ping = 3;</code>
     */
    boolean hasPing();
    /**
     * <pre>
     * a client (external) sanity check for testing
     * </pre>
     *
     * <code>optional bool ping = 3;</code>
     */
    boolean getPing();

    /**
     * <code>optional .Failure err = 5;</code>
     */
    boolean hasErr();
    /**
     * <code>optional .Failure err = 5;</code>
     */
    pipe.common.Common.Failure getErr();
    /**
     * <code>optional .Failure err = 5;</code>
     */
    pipe.common.Common.FailureOrBuilder getErrOrBuilder();

    /**
     * <code>optional .Request request = 6;</code>
     */
    boolean hasRequest();
    /**
     * <code>optional .Request request = 6;</code>
     */
    pipe.common.Common.Request getRequest();
    /**
     * <code>optional .Request request = 6;</code>
     */
    pipe.common.Common.RequestOrBuilder getRequestOrBuilder();

    /**
     * <code>optional .Response response = 7;</code>
     */
    boolean hasResponse();
    /**
     * <code>optional .Response response = 7;</code>
     */
    pipe.common.Common.Response getResponse();
    /**
     * <code>optional .Response response = 7;</code>
     */
    pipe.common.Common.ResponseOrBuilder getResponseOrBuilder();

    public routing.Pipe.CommandMessage.PayloadCase getPayloadCase();
  }
  /**
   * Protobuf type {@code CommandMessage}
   */
  public  static final class CommandMessage extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:CommandMessage)
      CommandMessageOrBuilder {
    // Use CommandMessage.newBuilder() to construct.
    private CommandMessage(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private CommandMessage() {
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    private CommandMessage(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!parseUnknownField(input, unknownFields,
                                     extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
            case 10: {
              pipe.common.Common.Header.Builder subBuilder = null;
              if (((bitField0_ & 0x00000001) == 0x00000001)) {
                subBuilder = header_.toBuilder();
              }
              header_ = input.readMessage(pipe.common.Common.Header.PARSER, extensionRegistry);
              if (subBuilder != null) {
                subBuilder.mergeFrom(header_);
                header_ = subBuilder.buildPartial();
              }
              bitField0_ |= 0x00000001;
              break;
            }
            case 24: {
              payloadCase_ = 3;
              payload_ = input.readBool();
              break;
            }
            case 42: {
              pipe.common.Common.Failure.Builder subBuilder = null;
              if (payloadCase_ == 5) {
                subBuilder = ((pipe.common.Common.Failure) payload_).toBuilder();
              }
              payload_ =
                  input.readMessage(pipe.common.Common.Failure.PARSER, extensionRegistry);
              if (subBuilder != null) {
                subBuilder.mergeFrom((pipe.common.Common.Failure) payload_);
                payload_ = subBuilder.buildPartial();
              }
              payloadCase_ = 5;
              break;
            }
            case 50: {
              pipe.common.Common.Request.Builder subBuilder = null;
              if (payloadCase_ == 6) {
                subBuilder = ((pipe.common.Common.Request) payload_).toBuilder();
              }
              payload_ =
                  input.readMessage(pipe.common.Common.Request.PARSER, extensionRegistry);
              if (subBuilder != null) {
                subBuilder.mergeFrom((pipe.common.Common.Request) payload_);
                payload_ = subBuilder.buildPartial();
              }
              payloadCase_ = 6;
              break;
            }
            case 58: {
              pipe.common.Common.Response.Builder subBuilder = null;
              if (payloadCase_ == 7) {
                subBuilder = ((pipe.common.Common.Response) payload_).toBuilder();
              }
              payload_ =
                  input.readMessage(pipe.common.Common.Response.PARSER, extensionRegistry);
              if (subBuilder != null) {
                subBuilder.mergeFrom((pipe.common.Common.Response) payload_);
                payload_ = subBuilder.buildPartial();
              }
              payloadCase_ = 7;
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return routing.Pipe.internal_static_CommandMessage_descriptor;
    }

    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return routing.Pipe.internal_static_CommandMessage_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              routing.Pipe.CommandMessage.class, routing.Pipe.CommandMessage.Builder.class);
    }

    private int bitField0_;
    private int payloadCase_ = 0;
    private java.lang.Object payload_;
    public enum PayloadCase
        implements com.google.protobuf.Internal.EnumLite {
      PING(3),
      ERR(5),
      REQUEST(6),
      RESPONSE(7),
      PAYLOAD_NOT_SET(0);
      private final int value;
      private PayloadCase(int value) {
        this.value = value;
      }
      /**
       * @deprecated Use {@link #forNumber(int)} instead.
       */
      @java.lang.Deprecated
      public static PayloadCase valueOf(int value) {
        return forNumber(value);
      }

      public static PayloadCase forNumber(int value) {
        switch (value) {
          case 3: return PING;
          case 5: return ERR;
          case 6: return REQUEST;
          case 7: return RESPONSE;
          case 0: return PAYLOAD_NOT_SET;
          default: return null;
        }
      }
      public int getNumber() {
        return this.value;
      }
    };

    public PayloadCase
    getPayloadCase() {
      return PayloadCase.forNumber(
          payloadCase_);
    }

    public static final int HEADER_FIELD_NUMBER = 1;
    private pipe.common.Common.Header header_;
    /**
     * <code>required .Header header = 1;</code>
     */
    public boolean hasHeader() {
      return ((bitField0_ & 0x00000001) == 0x00000001);
    }
    /**
     * <code>required .Header header = 1;</code>
     */
    public pipe.common.Common.Header getHeader() {
      return header_ == null ? pipe.common.Common.Header.getDefaultInstance() : header_;
    }
    /**
     * <code>required .Header header = 1;</code>
     */
    public pipe.common.Common.HeaderOrBuilder getHeaderOrBuilder() {
      return header_ == null ? pipe.common.Common.Header.getDefaultInstance() : header_;
    }

    public static final int PING_FIELD_NUMBER = 3;
    /**
     * <pre>
     * a client (external) sanity check for testing
     * </pre>
     *
     * <code>optional bool ping = 3;</code>
     */
    public boolean hasPing() {
      return payloadCase_ == 3;
    }
    /**
     * <pre>
     * a client (external) sanity check for testing
     * </pre>
     *
     * <code>optional bool ping = 3;</code>
     */
    public boolean getPing() {
      if (payloadCase_ == 3) {
        return (java.lang.Boolean) payload_;
      }
      return false;
    }

    public static final int ERR_FIELD_NUMBER = 5;
    /**
     * <code>optional .Failure err = 5;</code>
     */
    public boolean hasErr() {
      return payloadCase_ == 5;
    }
    /**
     * <code>optional .Failure err = 5;</code>
     */
    public pipe.common.Common.Failure getErr() {
      if (payloadCase_ == 5) {
         return (pipe.common.Common.Failure) payload_;
      }
      return pipe.common.Common.Failure.getDefaultInstance();
    }
    /**
     * <code>optional .Failure err = 5;</code>
     */
    public pipe.common.Common.FailureOrBuilder getErrOrBuilder() {
      if (payloadCase_ == 5) {
         return (pipe.common.Common.Failure) payload_;
      }
      return pipe.common.Common.Failure.getDefaultInstance();
    }

    public static final int REQUEST_FIELD_NUMBER = 6;
    /**
     * <code>optional .Request request = 6;</code>
     */
    public boolean hasRequest() {
      return payloadCase_ == 6;
    }
    /**
     * <code>optional .Request request = 6;</code>
     */
    public pipe.common.Common.Request getRequest() {
      if (payloadCase_ == 6) {
         return (pipe.common.Common.Request) payload_;
      }
      return pipe.common.Common.Request.getDefaultInstance();
    }
    /**
     * <code>optional .Request request = 6;</code>
     */
    public pipe.common.Common.RequestOrBuilder getRequestOrBuilder() {
      if (payloadCase_ == 6) {
         return (pipe.common.Common.Request) payload_;
      }
      return pipe.common.Common.Request.getDefaultInstance();
    }

    public static final int RESPONSE_FIELD_NUMBER = 7;
    /**
     * <code>optional .Response response = 7;</code>
     */
    public boolean hasResponse() {
      return payloadCase_ == 7;
    }
    /**
     * <code>optional .Response response = 7;</code>
     */
    public pipe.common.Common.Response getResponse() {
      if (payloadCase_ == 7) {
         return (pipe.common.Common.Response) payload_;
      }
      return pipe.common.Common.Response.getDefaultInstance();
    }
    /**
     * <code>optional .Response response = 7;</code>
     */
    public pipe.common.Common.ResponseOrBuilder getResponseOrBuilder() {
      if (payloadCase_ == 7) {
         return (pipe.common.Common.Response) payload_;
      }
      return pipe.common.Common.Response.getDefaultInstance();
    }

    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      if (!hasHeader()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (!getHeader().isInitialized()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (hasErr()) {
        if (!getErr().isInitialized()) {
          memoizedIsInitialized = 0;
          return false;
        }
      }
      if (hasRequest()) {
        if (!getRequest().isInitialized()) {
          memoizedIsInitialized = 0;
          return false;
        }
      }
      if (hasResponse()) {
        if (!getResponse().isInitialized()) {
          memoizedIsInitialized = 0;
          return false;
        }
      }
      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        output.writeMessage(1, getHeader());
      }
      if (payloadCase_ == 3) {
        output.writeBool(
            3, (boolean)((java.lang.Boolean) payload_));
      }
      if (payloadCase_ == 5) {
        output.writeMessage(5, (pipe.common.Common.Failure) payload_);
      }
      if (payloadCase_ == 6) {
        output.writeMessage(6, (pipe.common.Common.Request) payload_);
      }
      if (payloadCase_ == 7) {
        output.writeMessage(7, (pipe.common.Common.Response) payload_);
      }
      unknownFields.writeTo(output);
    }

    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(1, getHeader());
      }
      if (payloadCase_ == 3) {
        size += com.google.protobuf.CodedOutputStream
          .computeBoolSize(
              3, (boolean)((java.lang.Boolean) payload_));
      }
      if (payloadCase_ == 5) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(5, (pipe.common.Common.Failure) payload_);
      }
      if (payloadCase_ == 6) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(6, (pipe.common.Common.Request) payload_);
      }
      if (payloadCase_ == 7) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(7, (pipe.common.Common.Response) payload_);
      }
      size += unknownFields.getSerializedSize();
      memoizedSize = size;
      return size;
    }

    private static final long serialVersionUID = 0L;
    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof routing.Pipe.CommandMessage)) {
        return super.equals(obj);
      }
      routing.Pipe.CommandMessage other = (routing.Pipe.CommandMessage) obj;

      boolean result = true;
      result = result && (hasHeader() == other.hasHeader());
      if (hasHeader()) {
        result = result && getHeader()
            .equals(other.getHeader());
      }
      result = result && getPayloadCase().equals(
          other.getPayloadCase());
      if (!result) return false;
      switch (payloadCase_) {
        case 3:
          result = result && (getPing()
              == other.getPing());
          break;
        case 5:
          result = result && getErr()
              .equals(other.getErr());
          break;
        case 6:
          result = result && getRequest()
              .equals(other.getRequest());
          break;
        case 7:
          result = result && getResponse()
              .equals(other.getResponse());
          break;
        case 0:
        default:
      }
      result = result && unknownFields.equals(other.unknownFields);
      return result;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      if (hasHeader()) {
        hash = (37 * hash) + HEADER_FIELD_NUMBER;
        hash = (53 * hash) + getHeader().hashCode();
      }
      switch (payloadCase_) {
        case 3:
          hash = (37 * hash) + PING_FIELD_NUMBER;
          hash = (53 * hash) + com.google.protobuf.Internal.hashBoolean(
              getPing());
          break;
        case 5:
          hash = (37 * hash) + ERR_FIELD_NUMBER;
          hash = (53 * hash) + getErr().hashCode();
          break;
        case 6:
          hash = (37 * hash) + REQUEST_FIELD_NUMBER;
          hash = (53 * hash) + getRequest().hashCode();
          break;
        case 7:
          hash = (37 * hash) + RESPONSE_FIELD_NUMBER;
          hash = (53 * hash) + getResponse().hashCode();
          break;
        case 0:
        default:
      }
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static routing.Pipe.CommandMessage parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static routing.Pipe.CommandMessage parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static routing.Pipe.CommandMessage parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static routing.Pipe.CommandMessage parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static routing.Pipe.CommandMessage parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static routing.Pipe.CommandMessage parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static routing.Pipe.CommandMessage parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static routing.Pipe.CommandMessage parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static routing.Pipe.CommandMessage parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static routing.Pipe.CommandMessage parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(routing.Pipe.CommandMessage prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code CommandMessage}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:CommandMessage)
        routing.Pipe.CommandMessageOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return routing.Pipe.internal_static_CommandMessage_descriptor;
      }

      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return routing.Pipe.internal_static_CommandMessage_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                routing.Pipe.CommandMessage.class, routing.Pipe.CommandMessage.Builder.class);
      }

      // Construct using routing.Pipe.CommandMessage.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
          getHeaderFieldBuilder();
        }
      }
      public Builder clear() {
        super.clear();
        if (headerBuilder_ == null) {
          header_ = null;
        } else {
          headerBuilder_.clear();
        }
        bitField0_ = (bitField0_ & ~0x00000001);
        payloadCase_ = 0;
        payload_ = null;
        return this;
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return routing.Pipe.internal_static_CommandMessage_descriptor;
      }

      public routing.Pipe.CommandMessage getDefaultInstanceForType() {
        return routing.Pipe.CommandMessage.getDefaultInstance();
      }

      public routing.Pipe.CommandMessage build() {
        routing.Pipe.CommandMessage result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public routing.Pipe.CommandMessage buildPartial() {
        routing.Pipe.CommandMessage result = new routing.Pipe.CommandMessage(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (((from_bitField0_ & 0x00000001) == 0x00000001)) {
          to_bitField0_ |= 0x00000001;
        }
        if (headerBuilder_ == null) {
          result.header_ = header_;
        } else {
          result.header_ = headerBuilder_.build();
        }
        if (payloadCase_ == 3) {
          result.payload_ = payload_;
        }
        if (payloadCase_ == 5) {
          if (errBuilder_ == null) {
            result.payload_ = payload_;
          } else {
            result.payload_ = errBuilder_.build();
          }
        }
        if (payloadCase_ == 6) {
          if (requestBuilder_ == null) {
            result.payload_ = payload_;
          } else {
            result.payload_ = requestBuilder_.build();
          }
        }
        if (payloadCase_ == 7) {
          if (responseBuilder_ == null) {
            result.payload_ = payload_;
          } else {
            result.payload_ = responseBuilder_.build();
          }
        }
        result.bitField0_ = to_bitField0_;
        result.payloadCase_ = payloadCase_;
        onBuilt();
        return result;
      }

      public Builder clone() {
        return (Builder) super.clone();
      }
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          Object value) {
        return (Builder) super.setField(field, value);
      }
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return (Builder) super.clearField(field);
      }
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return (Builder) super.clearOneof(oneof);
      }
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, Object value) {
        return (Builder) super.setRepeatedField(field, index, value);
      }
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          Object value) {
        return (Builder) super.addRepeatedField(field, value);
      }
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof routing.Pipe.CommandMessage) {
          return mergeFrom((routing.Pipe.CommandMessage)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(routing.Pipe.CommandMessage other) {
        if (other == routing.Pipe.CommandMessage.getDefaultInstance()) return this;
        if (other.hasHeader()) {
          mergeHeader(other.getHeader());
        }
        switch (other.getPayloadCase()) {
          case PING: {
            setPing(other.getPing());
            break;
          }
          case ERR: {
            mergeErr(other.getErr());
            break;
          }
          case REQUEST: {
            mergeRequest(other.getRequest());
            break;
          }
          case RESPONSE: {
            mergeResponse(other.getResponse());
            break;
          }
          case PAYLOAD_NOT_SET: {
            break;
          }
        }
        this.mergeUnknownFields(other.unknownFields);
        onChanged();
        return this;
      }

      public final boolean isInitialized() {
        if (!hasHeader()) {
          return false;
        }
        if (!getHeader().isInitialized()) {
          return false;
        }
        if (hasErr()) {
          if (!getErr().isInitialized()) {
            return false;
          }
        }
        if (hasRequest()) {
          if (!getRequest().isInitialized()) {
            return false;
          }
        }
        if (hasResponse()) {
          if (!getResponse().isInitialized()) {
            return false;
          }
        }
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        routing.Pipe.CommandMessage parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (routing.Pipe.CommandMessage) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int payloadCase_ = 0;
      private java.lang.Object payload_;
      public PayloadCase
          getPayloadCase() {
        return PayloadCase.forNumber(
            payloadCase_);
      }

      public Builder clearPayload() {
        payloadCase_ = 0;
        payload_ = null;
        onChanged();
        return this;
      }

      private int bitField0_;

      private pipe.common.Common.Header header_ = null;
      private com.google.protobuf.SingleFieldBuilderV3<
          pipe.common.Common.Header, pipe.common.Common.Header.Builder, pipe.common.Common.HeaderOrBuilder> headerBuilder_;
      /**
       * <code>required .Header header = 1;</code>
       */
      public boolean hasHeader() {
        return ((bitField0_ & 0x00000001) == 0x00000001);
      }
      /**
       * <code>required .Header header = 1;</code>
       */
      public pipe.common.Common.Header getHeader() {
        if (headerBuilder_ == null) {
          return header_ == null ? pipe.common.Common.Header.getDefaultInstance() : header_;
        } else {
          return headerBuilder_.getMessage();
        }
      }
      /**
       * <code>required .Header header = 1;</code>
       */
      public Builder setHeader(pipe.common.Common.Header value) {
        if (headerBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          header_ = value;
          onChanged();
        } else {
          headerBuilder_.setMessage(value);
        }
        bitField0_ |= 0x00000001;
        return this;
      }
      /**
       * <code>required .Header header = 1;</code>
       */
      public Builder setHeader(
          pipe.common.Common.Header.Builder builderForValue) {
        if (headerBuilder_ == null) {
          header_ = builderForValue.build();
          onChanged();
        } else {
          headerBuilder_.setMessage(builderForValue.build());
        }
        bitField0_ |= 0x00000001;
        return this;
      }
      /**
       * <code>required .Header header = 1;</code>
       */
      public Builder mergeHeader(pipe.common.Common.Header value) {
        if (headerBuilder_ == null) {
          if (((bitField0_ & 0x00000001) == 0x00000001) &&
              header_ != null &&
              header_ != pipe.common.Common.Header.getDefaultInstance()) {
            header_ =
              pipe.common.Common.Header.newBuilder(header_).mergeFrom(value).buildPartial();
          } else {
            header_ = value;
          }
          onChanged();
        } else {
          headerBuilder_.mergeFrom(value);
        }
        bitField0_ |= 0x00000001;
        return this;
      }
      /**
       * <code>required .Header header = 1;</code>
       */
      public Builder clearHeader() {
        if (headerBuilder_ == null) {
          header_ = null;
          onChanged();
        } else {
          headerBuilder_.clear();
        }
        bitField0_ = (bitField0_ & ~0x00000001);
        return this;
      }
      /**
       * <code>required .Header header = 1;</code>
       */
      public pipe.common.Common.Header.Builder getHeaderBuilder() {
        bitField0_ |= 0x00000001;
        onChanged();
        return getHeaderFieldBuilder().getBuilder();
      }
      /**
       * <code>required .Header header = 1;</code>
       */
      public pipe.common.Common.HeaderOrBuilder getHeaderOrBuilder() {
        if (headerBuilder_ != null) {
          return headerBuilder_.getMessageOrBuilder();
        } else {
          return header_ == null ?
              pipe.common.Common.Header.getDefaultInstance() : header_;
        }
      }
      /**
       * <code>required .Header header = 1;</code>
       */
      private com.google.protobuf.SingleFieldBuilderV3<
          pipe.common.Common.Header, pipe.common.Common.Header.Builder, pipe.common.Common.HeaderOrBuilder> 
          getHeaderFieldBuilder() {
        if (headerBuilder_ == null) {
          headerBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
              pipe.common.Common.Header, pipe.common.Common.Header.Builder, pipe.common.Common.HeaderOrBuilder>(
                  getHeader(),
                  getParentForChildren(),
                  isClean());
          header_ = null;
        }
        return headerBuilder_;
      }

      /**
       * <pre>
       * a client (external) sanity check for testing
       * </pre>
       *
       * <code>optional bool ping = 3;</code>
       */
      public boolean hasPing() {
        return payloadCase_ == 3;
      }
      /**
       * <pre>
       * a client (external) sanity check for testing
       * </pre>
       *
       * <code>optional bool ping = 3;</code>
       */
      public boolean getPing() {
        if (payloadCase_ == 3) {
          return (java.lang.Boolean) payload_;
        }
        return false;
      }
      /**
       * <pre>
       * a client (external) sanity check for testing
       * </pre>
       *
       * <code>optional bool ping = 3;</code>
       */
      public Builder setPing(boolean value) {
        payloadCase_ = 3;
        payload_ = value;
        onChanged();
        return this;
      }
      /**
       * <pre>
       * a client (external) sanity check for testing
       * </pre>
       *
       * <code>optional bool ping = 3;</code>
       */
      public Builder clearPing() {
        if (payloadCase_ == 3) {
          payloadCase_ = 0;
          payload_ = null;
          onChanged();
        }
        return this;
      }

      private com.google.protobuf.SingleFieldBuilderV3<
          pipe.common.Common.Failure, pipe.common.Common.Failure.Builder, pipe.common.Common.FailureOrBuilder> errBuilder_;
      /**
       * <code>optional .Failure err = 5;</code>
       */
      public boolean hasErr() {
        return payloadCase_ == 5;
      }
      /**
       * <code>optional .Failure err = 5;</code>
       */
      public pipe.common.Common.Failure getErr() {
        if (errBuilder_ == null) {
          if (payloadCase_ == 5) {
            return (pipe.common.Common.Failure) payload_;
          }
          return pipe.common.Common.Failure.getDefaultInstance();
        } else {
          if (payloadCase_ == 5) {
            return errBuilder_.getMessage();
          }
          return pipe.common.Common.Failure.getDefaultInstance();
        }
      }
      /**
       * <code>optional .Failure err = 5;</code>
       */
      public Builder setErr(pipe.common.Common.Failure value) {
        if (errBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          payload_ = value;
          onChanged();
        } else {
          errBuilder_.setMessage(value);
        }
        payloadCase_ = 5;
        return this;
      }
      /**
       * <code>optional .Failure err = 5;</code>
       */
      public Builder setErr(
          pipe.common.Common.Failure.Builder builderForValue) {
        if (errBuilder_ == null) {
          payload_ = builderForValue.build();
          onChanged();
        } else {
          errBuilder_.setMessage(builderForValue.build());
        }
        payloadCase_ = 5;
        return this;
      }
      /**
       * <code>optional .Failure err = 5;</code>
       */
      public Builder mergeErr(pipe.common.Common.Failure value) {
        if (errBuilder_ == null) {
          if (payloadCase_ == 5 &&
              payload_ != pipe.common.Common.Failure.getDefaultInstance()) {
            payload_ = pipe.common.Common.Failure.newBuilder((pipe.common.Common.Failure) payload_)
                .mergeFrom(value).buildPartial();
          } else {
            payload_ = value;
          }
          onChanged();
        } else {
          if (payloadCase_ == 5) {
            errBuilder_.mergeFrom(value);
          }
          errBuilder_.setMessage(value);
        }
        payloadCase_ = 5;
        return this;
      }
      /**
       * <code>optional .Failure err = 5;</code>
       */
      public Builder clearErr() {
        if (errBuilder_ == null) {
          if (payloadCase_ == 5) {
            payloadCase_ = 0;
            payload_ = null;
            onChanged();
          }
        } else {
          if (payloadCase_ == 5) {
            payloadCase_ = 0;
            payload_ = null;
          }
          errBuilder_.clear();
        }
        return this;
      }
      /**
       * <code>optional .Failure err = 5;</code>
       */
      public pipe.common.Common.Failure.Builder getErrBuilder() {
        return getErrFieldBuilder().getBuilder();
      }
      /**
       * <code>optional .Failure err = 5;</code>
       */
      public pipe.common.Common.FailureOrBuilder getErrOrBuilder() {
        if ((payloadCase_ == 5) && (errBuilder_ != null)) {
          return errBuilder_.getMessageOrBuilder();
        } else {
          if (payloadCase_ == 5) {
            return (pipe.common.Common.Failure) payload_;
          }
          return pipe.common.Common.Failure.getDefaultInstance();
        }
      }
      /**
       * <code>optional .Failure err = 5;</code>
       */
      private com.google.protobuf.SingleFieldBuilderV3<
          pipe.common.Common.Failure, pipe.common.Common.Failure.Builder, pipe.common.Common.FailureOrBuilder> 
          getErrFieldBuilder() {
        if (errBuilder_ == null) {
          if (!(payloadCase_ == 5)) {
            payload_ = pipe.common.Common.Failure.getDefaultInstance();
          }
          errBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
              pipe.common.Common.Failure, pipe.common.Common.Failure.Builder, pipe.common.Common.FailureOrBuilder>(
                  (pipe.common.Common.Failure) payload_,
                  getParentForChildren(),
                  isClean());
          payload_ = null;
        }
        payloadCase_ = 5;
        onChanged();;
        return errBuilder_;
      }

      private com.google.protobuf.SingleFieldBuilderV3<
          pipe.common.Common.Request, pipe.common.Common.Request.Builder, pipe.common.Common.RequestOrBuilder> requestBuilder_;
      /**
       * <code>optional .Request request = 6;</code>
       */
      public boolean hasRequest() {
        return payloadCase_ == 6;
      }
      /**
       * <code>optional .Request request = 6;</code>
       */
      public pipe.common.Common.Request getRequest() {
        if (requestBuilder_ == null) {
          if (payloadCase_ == 6) {
            return (pipe.common.Common.Request) payload_;
          }
          return pipe.common.Common.Request.getDefaultInstance();
        } else {
          if (payloadCase_ == 6) {
            return requestBuilder_.getMessage();
          }
          return pipe.common.Common.Request.getDefaultInstance();
        }
      }
      /**
       * <code>optional .Request request = 6;</code>
       */
      public Builder setRequest(pipe.common.Common.Request value) {
        if (requestBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          payload_ = value;
          onChanged();
        } else {
          requestBuilder_.setMessage(value);
        }
        payloadCase_ = 6;
        return this;
      }
      /**
       * <code>optional .Request request = 6;</code>
       */
      public Builder setRequest(
          pipe.common.Common.Request.Builder builderForValue) {
        if (requestBuilder_ == null) {
          payload_ = builderForValue.build();
          onChanged();
        } else {
          requestBuilder_.setMessage(builderForValue.build());
        }
        payloadCase_ = 6;
        return this;
      }
      /**
       * <code>optional .Request request = 6;</code>
       */
      public Builder mergeRequest(pipe.common.Common.Request value) {
        if (requestBuilder_ == null) {
          if (payloadCase_ == 6 &&
              payload_ != pipe.common.Common.Request.getDefaultInstance()) {
            payload_ = pipe.common.Common.Request.newBuilder((pipe.common.Common.Request) payload_)
                .mergeFrom(value).buildPartial();
          } else {
            payload_ = value;
          }
          onChanged();
        } else {
          if (payloadCase_ == 6) {
            requestBuilder_.mergeFrom(value);
          }
          requestBuilder_.setMessage(value);
        }
        payloadCase_ = 6;
        return this;
      }
      /**
       * <code>optional .Request request = 6;</code>
       */
      public Builder clearRequest() {
        if (requestBuilder_ == null) {
          if (payloadCase_ == 6) {
            payloadCase_ = 0;
            payload_ = null;
            onChanged();
          }
        } else {
          if (payloadCase_ == 6) {
            payloadCase_ = 0;
            payload_ = null;
          }
          requestBuilder_.clear();
        }
        return this;
      }
      /**
       * <code>optional .Request request = 6;</code>
       */
      public pipe.common.Common.Request.Builder getRequestBuilder() {
        return getRequestFieldBuilder().getBuilder();
      }
      /**
       * <code>optional .Request request = 6;</code>
       */
      public pipe.common.Common.RequestOrBuilder getRequestOrBuilder() {
        if ((payloadCase_ == 6) && (requestBuilder_ != null)) {
          return requestBuilder_.getMessageOrBuilder();
        } else {
          if (payloadCase_ == 6) {
            return (pipe.common.Common.Request) payload_;
          }
          return pipe.common.Common.Request.getDefaultInstance();
        }
      }
      /**
       * <code>optional .Request request = 6;</code>
       */
      private com.google.protobuf.SingleFieldBuilderV3<
          pipe.common.Common.Request, pipe.common.Common.Request.Builder, pipe.common.Common.RequestOrBuilder> 
          getRequestFieldBuilder() {
        if (requestBuilder_ == null) {
          if (!(payloadCase_ == 6)) {
            payload_ = pipe.common.Common.Request.getDefaultInstance();
          }
          requestBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
              pipe.common.Common.Request, pipe.common.Common.Request.Builder, pipe.common.Common.RequestOrBuilder>(
                  (pipe.common.Common.Request) payload_,
                  getParentForChildren(),
                  isClean());
          payload_ = null;
        }
        payloadCase_ = 6;
        onChanged();;
        return requestBuilder_;
      }

      private com.google.protobuf.SingleFieldBuilderV3<
          pipe.common.Common.Response, pipe.common.Common.Response.Builder, pipe.common.Common.ResponseOrBuilder> responseBuilder_;
      /**
       * <code>optional .Response response = 7;</code>
       */
      public boolean hasResponse() {
        return payloadCase_ == 7;
      }
      /**
       * <code>optional .Response response = 7;</code>
       */
      public pipe.common.Common.Response getResponse() {
        if (responseBuilder_ == null) {
          if (payloadCase_ == 7) {
            return (pipe.common.Common.Response) payload_;
          }
          return pipe.common.Common.Response.getDefaultInstance();
        } else {
          if (payloadCase_ == 7) {
            return responseBuilder_.getMessage();
          }
          return pipe.common.Common.Response.getDefaultInstance();
        }
      }
      /**
       * <code>optional .Response response = 7;</code>
       */
      public Builder setResponse(pipe.common.Common.Response value) {
        if (responseBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          payload_ = value;
          onChanged();
        } else {
          responseBuilder_.setMessage(value);
        }
        payloadCase_ = 7;
        return this;
      }
      /**
       * <code>optional .Response response = 7;</code>
       */
      public Builder setResponse(
          pipe.common.Common.Response.Builder builderForValue) {
        if (responseBuilder_ == null) {
          payload_ = builderForValue.build();
          onChanged();
        } else {
          responseBuilder_.setMessage(builderForValue.build());
        }
        payloadCase_ = 7;
        return this;
      }
      /**
       * <code>optional .Response response = 7;</code>
       */
      public Builder mergeResponse(pipe.common.Common.Response value) {
        if (responseBuilder_ == null) {
          if (payloadCase_ == 7 &&
              payload_ != pipe.common.Common.Response.getDefaultInstance()) {
            payload_ = pipe.common.Common.Response.newBuilder((pipe.common.Common.Response) payload_)
                .mergeFrom(value).buildPartial();
          } else {
            payload_ = value;
          }
          onChanged();
        } else {
          if (payloadCase_ == 7) {
            responseBuilder_.mergeFrom(value);
          }
          responseBuilder_.setMessage(value);
        }
        payloadCase_ = 7;
        return this;
      }
      /**
       * <code>optional .Response response = 7;</code>
       */
      public Builder clearResponse() {
        if (responseBuilder_ == null) {
          if (payloadCase_ == 7) {
            payloadCase_ = 0;
            payload_ = null;
            onChanged();
          }
        } else {
          if (payloadCase_ == 7) {
            payloadCase_ = 0;
            payload_ = null;
          }
          responseBuilder_.clear();
        }
        return this;
      }
      /**
       * <code>optional .Response response = 7;</code>
       */
      public pipe.common.Common.Response.Builder getResponseBuilder() {
        return getResponseFieldBuilder().getBuilder();
      }
      /**
       * <code>optional .Response response = 7;</code>
       */
      public pipe.common.Common.ResponseOrBuilder getResponseOrBuilder() {
        if ((payloadCase_ == 7) && (responseBuilder_ != null)) {
          return responseBuilder_.getMessageOrBuilder();
        } else {
          if (payloadCase_ == 7) {
            return (pipe.common.Common.Response) payload_;
          }
          return pipe.common.Common.Response.getDefaultInstance();
        }
      }
      /**
       * <code>optional .Response response = 7;</code>
       */
      private com.google.protobuf.SingleFieldBuilderV3<
          pipe.common.Common.Response, pipe.common.Common.Response.Builder, pipe.common.Common.ResponseOrBuilder> 
          getResponseFieldBuilder() {
        if (responseBuilder_ == null) {
          if (!(payloadCase_ == 7)) {
            payload_ = pipe.common.Common.Response.getDefaultInstance();
          }
          responseBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
              pipe.common.Common.Response, pipe.common.Common.Response.Builder, pipe.common.Common.ResponseOrBuilder>(
                  (pipe.common.Common.Response) payload_,
                  getParentForChildren(),
                  isClean());
          payload_ = null;
        }
        payloadCase_ = 7;
        onChanged();;
        return responseBuilder_;
      }
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFields(unknownFields);
      }

      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:CommandMessage)
    }

    // @@protoc_insertion_point(class_scope:CommandMessage)
    private static final routing.Pipe.CommandMessage DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new routing.Pipe.CommandMessage();
    }

    public static routing.Pipe.CommandMessage getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    @java.lang.Deprecated public static final com.google.protobuf.Parser<CommandMessage>
        PARSER = new com.google.protobuf.AbstractParser<CommandMessage>() {
      public CommandMessage parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
          return new CommandMessage(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<CommandMessage> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<CommandMessage> getParserForType() {
      return PARSER;
    }

    public routing.Pipe.CommandMessage getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_CommandMessage_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_CommandMessage_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\npipe.proto\032\014common.proto\"\231\001\n\016CommandMe" +
      "ssage\022\027\n\006header\030\001 \002(\0132\007.Header\022\016\n\004ping\030\003" +
      " \001(\010H\000\022\027\n\003err\030\005 \001(\0132\010.FailureH\000\022\033\n\007reque" +
      "st\030\006 \001(\0132\010.RequestH\000\022\035\n\010response\030\007 \001(\0132\t" +
      ".ResponseH\000B\t\n\007payloadB\013\n\007routingH\001"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
        new com.google.protobuf.Descriptors.FileDescriptor.    InternalDescriptorAssigner() {
          public com.google.protobuf.ExtensionRegistry assignDescriptors(
              com.google.protobuf.Descriptors.FileDescriptor root) {
            descriptor = root;
            return null;
          }
        };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
          pipe.common.Common.getDescriptor(),
        }, assigner);
    internal_static_CommandMessage_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_CommandMessage_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_CommandMessage_descriptor,
        new java.lang.String[] { "Header", "Ping", "Err", "Request", "Response", "Payload", });
    pipe.common.Common.getDescriptor();
  }

  // @@protoc_insertion_point(outer_class_scope)
}
